### ISSUE TITLE
make install failed on bionic!

### ISSUE THREAD

**Issue by aneeshpanoli** [civictechhub/api#15]
Any idea what's wrong?

`usermod: invalid user ID '$(id'
ERROR: Service 'api' failed to build: The command '/bin/sh -c usermod -u ${WWW_DATA_USER_ID} www-data && groupmod -g ${WWW_DATA_GROUP_ID} www-data' returned a non-zero code: 3
Makefile:2: recipe for target 'install' failed
make: *** [install] Error 1
`

**Comment by aneeshpanoli** [comment]
coming from [https://github.com/civictechhub/api/blob/08c6b99f116298d9ec17fe76137c9817803a5e1b/docker/src/api.Dockerfile#L63](url)

**Comment by geiru** [comment]
Did you try this in master or develop? There was a bug in master, i just merged. Should befixed now.

**Comment by geiru** [comment]
Could you please try again?

**Comment by aneeshpanoli** [comment]
I pulled master. Now this is the error I get.
` => ERROR [development 7/9] RUN usermod -u 0 www-data && groupmod -g 0 www-data                                                                          0.6s 
------                                                                                                                                                        
 > [development 7/9] RUN usermod -u 0 www-data && groupmod -g 0 www-data:                                                                                     
#20 0.527 usermod: UID '0' already exists                                                                                                                     
------                                                                                                                                                        
failed to solve with frontend dockerfile.v0: failed to build LLB: executor failed running [/bin/sh -c usermod -u ${WWW_DATA_USER_ID} www-data && groupmod -g ${WWW_DATA_GROUP_ID} www-data]: runc did not terminate sucessfully
Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 72, in main
  File "compose/cli/main.py", line 128, in perform_command
  File "compose/cli/main.py", line 303, in build
  File "compose/project.py", line 403, in build
  File "compose/project.py", line 385, in build_service
  File "compose/service.py", line 1110, in build
  File "compose/progress_stream.py", line 25, in stream_output
  File "compose/utils.py", line 61, in split_buffer
  File "compose/utils.py", line 37, in stream_as_text
  File "compose/service.py", line 1818, in build
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp563951f9'
[10216] Failed to execute script docker-compose
`

**Comment by aneeshpanoli** [comment]
A few hints here -
[`](https://stackoverflow.com/questions/44592372/usermod-uid-0-already-exists-why)

**Comment by geiru** [comment]
Looks like you are running the install script as root. Wouldn't advise that.  

Anyways, i added a check for this in develop. Could you please pull and try again?

**Comment by aneeshpanoli** [comment]
I am sorry! its the `sudo` that broke everything on my side.
Found it [here](https://github.com/shipping-docker/vessel/issues/71#issuecomment-377207684)
