### ISSUE TITLE
Add missing tables and fields to airtable import script

### ISSUE THREAD

**Issue by geiru** [civictechhub/api#8]
The airtable import script is a python script found here app/py_scripts/airtable2sql/airtable_to_sql.py.

The following things need to be added:
1. resources (map to service links in the mysql database) are missing
2. group.logo_url is missing
3. as we plan to also import from different datasources, the existing groups should not be deleted but there should be a detection mechanism for already imported groups

Regarding 3. we could either start by simple comparing the group names. Or we could add `foreign_key` and `datasource` fields to table `group` to detect already imported groups.

**Comment by francomor** [comment]
I actually do 1 and 2.

**Comment by geiru** [comment]
Works great, thanks.

**Comment by geiru** [comment]
Nice work.
